js/screens/HomeScreen.js
the current behavior of sortable listview is buggy, especially combined with `RefreshControl`, make it nearly useless, so I tweaked it a bit.
I've landed several fixed to `Sortable-ListView`, although I'm one of the collaborators, but I don't have the right to publish a new version, so please make sure to update that package against the latest master branch
=> fix sortable listview

.prettierrc, js/Discourse.js, js/DiscourseUtils.js, js/ProgressBar.js, js/screens/HomeScreen.js, js/screens/HomeScreenComponents/DebugRow.js, js/screens/HomeScreenComponents/NavigationBar.js, js/screens/HomeScreenComponents/Notification.js, js/screens/HomeScreenComponents/OnBoardingView.js, js/screens/HomeScreenComponents/SiteRow.js, js/screens/HomeScreenComponents/TermBar.js, js/screens/NotificationsScreen.js, js/screens/NotificationsScreenComponents/EmptyNotificationsView.js, js/screens/NotificationsScreenComponents/Filter.android.js, js/screens/NotificationsScreenComponents/Filter.ios.js, js/screens/NotificationsScreenComponents/NavigationBar.js, js/screens/NotificationsScreenComponents/NotificationRow.js, js/site.js, js/site_manager.js, package-lock.json, package.json, yarn.lock
not sure is this accepted, but I always see different code style when I contribute to this code base
I use Prettier in all my js projects
=> run prettier

Gemfile.lock, android/app/build.gradle, fastlane/Fastfile, fastlane/Matchfile, ios/Discourse.xcodeproj/project.pbxproj, ios/Discourse/Info.plist, ios/ShareExtension/Info.plist, js/Discourse.js, js/locale/en.json, js/screens/HomeScreen.js, js/screens/HomeScreenComponents/TermBar.js
Also updates `fastlane-plugin-versioning` dependency and Android version ID.
=> UX: Minor changes to search term input

fastlane/Fastfile, ios/Discourse.xcodeproj/project.pbxproj, ios/Discourse/Info.plist, ios/ShareExtension/Info.plist, js/Discourse.js
Also some cleanup and version bumps.
=> FEATURE: Enable sound alerts for push notifications

ios/Discourse/AppDelegate.m, ios/Discourse/Info.plist, ios/Podfile.lock, js/Discourse.js, js/screens/HomeScreen.js, package.json, yarn.lock
Every time you open a site on iOS from the home screen, it will be donated to Siri. Which then can intelligently recommend that shortcut to you in the right context. 
This also disables Universal Links integration, we don't use them.
=> FEATURE: Support Siri Shortcuts

ios/Discourse.xcodeproj/project.pbxproj, ios/Discourse/AppDelegate.m, ios/Discourse/Info.plist, ios/DiscourseKeyboardShortcuts.h, ios/DiscourseKeyboardShortcuts.m, ios/ShareExtension/Info.plist, ios/ShareExtension/ShareExtension.entitlements, js/Discourse.js, js/screens/WebViewScreen.js, js/site_manager.js
Adds domain names to  the File menu UI. 
And does some minor method renaming.
=> Keyboard shortcut refactoring

ios/ShareExtension/Info.plist
=> DEV: Fix ShareExtension version

package.json, yarn.lock
Fixes the webview padding on iPhone 14 Pro
=> FIX: Update react-native-device-info

ios/Discourse/AppDelegate.m
=> DEV: Remove unused code path

ios/Podfile.lock, package.json, yarn.lock
Breaking changes should not affect our app
=> DEV: Update react-native-vector-icons

js/ProgressBar.js
We eventually want to migrate all our components from classes to functions – it's the way of the React's future 🥲 and a requirement to use hooks (and third-party libraries now often come in form of hooks)
The migration is a manual process so it will take time, but this component was simple enough so here's our first (?) react component function! 😃
=> DEV: Rewrite ProgressBar to a component func

js/screens/HomeScreenComponents/OnBoardingView.js
And slightly rework the view tree (to remove `{'\n'}`)
=> DEV: Convert OnboardingView to a function

package.json, yarn.lock
Just the og package, not react-native. That's a more difficult jump 😅
=> DEV: Update react

js/screens/HomeScreenComponents/DebugRow.js, js/site_manager.js
…and remove unused code. `themeOverride` state probably isn't needed either but I'm keeping it for now, just in case I missed something
=> DEV: Convert `DebugRow` to a function

.github/workflows/linting.yml, .prettierrc.js, _editorconfig, package.json
Also, remove editorconfig (unused) and update deprecated eslint config option.
=> DEV: Update npm scripts

js/Discourse.js
@pmusaraj I'm not sure about the language codes. Please double check that "pt-BR",  "zh-CN" and "zh-TW" actually works.
=> DEV: Add additional languages

js/DiscourseUtils.js, js/locale/en.json, js/screens/NotificationsScreenComponents/NotificationRow.js
25 - reaction
36 - post for watched category or tag
800 - user started following you
801 - user who you follow created a topic
802 - user who you follow replied
Before:
After:
=> FIX: add missing notifications

js/DiscourseUtils.js, js/locale/en.json, js/screens/NotificationsScreenComponents/NotificationRow.js
New notification type introduced to Core in this PR  - https://github.com/discourse/discourse/pull/19460
=> FIX: missing new feature notification type

js/Discourse.js
Methods called on wrong objects in 765370a5d904450cf85f68351fa139f043f3c596 :)
=> FIX: `componentWillUnmount` regressions

js/site.js
c.f. https://github.com/discourse/discourse/pull/22893
=> DEV: Remove unread_private_messages usage

android/app/build.gradle, android/build.gradle, ios/Discourse.xcodeproj/project.pbxproj, ios/Discourse/Info.plist, ios/ShareExtension/Info.plist, js/screens/HomeScreen.js, js/screens/NotificationsScreen.js
- Notifications change means that the Home screen pill counts do not get cleared when viewing the Notifications screen
- Android fix relates to https://meta.discourse.org/t/bugs-in-discoursehub-for-android/318870/12?u=pmusaraj 
Easier to review commit-by-commit.
=> Fixes to notifications screen and Android settings on non-English devices
